//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public string MAHD { get; set; }
        public string MADH { get; set; }
        public string MAU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    
        public virtual DONGHO DONGHO { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
