//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAP
    {
        public int MAN { get; set; }
        public string MADH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<decimal> DONGIANHAP { get; set; }
        public Nullable<decimal> TONGTIENNHAP { get; set; }
        public string MANHACUNGCAP { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHAP NHAP { get; set; }
    }
}
