//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONGHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONGHO()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public string MADH { get; set; }
        public string TENDH { get; set; }
        public string MAU { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public string MALOAIDH { get; set; }
        public string MANHACUNGCAP { get; set; }
        public Nullable<int> TONKHO { get; set; }
        public string HINHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual LOAIDONGHO LOAIDONGHO { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
